#!/bin/bash
rm -rf /etc/pki/ca-trust/source/anchors/*
cp /etc/grid-security/certificates/*.pem /etc/pki/ca-trust/source/anchors/
cp /usr/local/etc/pki/*.pem /etc/pki/ca-trust/source/anchors/
update-ca-trust
if [ -f /etc/nagios/globus/robotcert.pem ]; then
  cat /etc/nagios/globus/robotcert.pem >> /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
fi